// SPDX-FileCopyrightText: 2024 TPT Solutions
// SPDX-License-Identifier: MIT OR Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: tpt/v1/tpt.proto

// Package tpt.v1 — the TPT DataCenter core platform gRPC contract (todo.md
// Phase 8). It ties together the edge control surface, the hardware management
// API, the telemetry query path, and the grid-stress signal so a single
// orchestration service can route commands, enforce policy, and audit every
// action.
//
// Auth model: every mutating RPC expects a valid Bearer token in the
// `authorization` request header (mapped by the gateway to the `operator`
// field). Read RPCs under /telemetry and /grid are bearer-optional per
// deployment.

package tptv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceKind mirrors rust_edge::hal::types::DeviceKind.
type DeviceKind int32

const (
	DeviceKind_DEVICE_KIND_UNSPECIFIED DeviceKind = 0
	DeviceKind_RACK                    DeviceKind = 1
	DeviceKind_PDU                     DeviceKind = 2
	DeviceKind_UPS                     DeviceKind = 3
	DeviceKind_COOLING_LOOP            DeviceKind = 4
	DeviceKind_SERVER                  DeviceKind = 5
)

// Enum value maps for DeviceKind.
var (
	DeviceKind_name = map[int32]string{
		0: "DEVICE_KIND_UNSPECIFIED",
		1: "RACK",
		2: "PDU",
		3: "UPS",
		4: "COOLING_LOOP",
		5: "SERVER",
	}
	DeviceKind_value = map[string]int32{
		"DEVICE_KIND_UNSPECIFIED": 0,
		"RACK":                    1,
		"PDU":                     2,
		"UPS":                     3,
		"COOLING_LOOP":            4,
		"SERVER":                  5,
	}
)

func (x DeviceKind) Enum() *DeviceKind {
	p := new(DeviceKind)
	*p = x
	return p
}

func (x DeviceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tpt_v1_tpt_proto_enumTypes[0].Descriptor()
}

func (DeviceKind) Type() protoreflect.EnumType {
	return &file_tpt_v1_tpt_proto_enumTypes[0]
}

func (x DeviceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceKind.Descriptor instead.
func (DeviceKind) EnumDescriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{0}
}

// ActuatorCommand mirrors the control override channels.
type Command int32

const (
	Command_COMMAND_UNSPECIFIED Command = 0
	Command_VALVE               Command = 1 // cooling valve position, 0..100 % open
	Command_FAN                 Command = 2 // cooling fan speed, 0..100 % of max
	Command_OUTLET              Command = 3 // PDU outlet on/off
	Command_DISCHARGE_LIMIT     Command = 4 // UPS max discharge rate, 0..100 % of capacity
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "COMMAND_UNSPECIFIED",
		1: "VALVE",
		2: "FAN",
		3: "OUTLET",
		4: "DISCHARGE_LIMIT",
	}
	Command_value = map[string]int32{
		"COMMAND_UNSPECIFIED": 0,
		"VALVE":               1,
		"FAN":                 2,
		"OUTLET":              3,
		"DISCHARGE_LIMIT":     4,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_tpt_v1_tpt_proto_enumTypes[1].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_tpt_v1_tpt_proto_enumTypes[1]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{1}
}

// Mode describes how a device is currently driven.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_AUTO             Mode = 1 // edge supervisor / AI brain in control
	Mode_MANUAL           Mode = 2 // operator override active
	Mode_SAFE             Mode = 3 // latched into fail-safe state
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "AUTO",
		2: "MANUAL",
		3: "SAFE",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"AUTO":             1,
		"MANUAL":           2,
		"SAFE":             3,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_tpt_v1_tpt_proto_enumTypes[2].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_tpt_v1_tpt_proto_enumTypes[2]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{2}
}

// GridStressLevel mirrors hardware.GridStressLevel.
type GridStressLevel int32

const (
	GridStressLevel_GRID_STRESS_UNSPECIFIED GridStressLevel = 0
	GridStressLevel_NONE                    GridStressLevel = 1
	GridStressLevel_MILD                    GridStressLevel = 2
	GridStressLevel_HIGH                    GridStressLevel = 3
	GridStressLevel_CRITICAL                GridStressLevel = 4
)

// Enum value maps for GridStressLevel.
var (
	GridStressLevel_name = map[int32]string{
		0: "GRID_STRESS_UNSPECIFIED",
		1: "NONE",
		2: "MILD",
		3: "HIGH",
		4: "CRITICAL",
	}
	GridStressLevel_value = map[string]int32{
		"GRID_STRESS_UNSPECIFIED": 0,
		"NONE":                    1,
		"MILD":                    2,
		"HIGH":                    3,
		"CRITICAL":                4,
	}
)

func (x GridStressLevel) Enum() *GridStressLevel {
	p := new(GridStressLevel)
	*p = x
	return p
}

func (x GridStressLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GridStressLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_tpt_v1_tpt_proto_enumTypes[3].Descriptor()
}

func (GridStressLevel) Type() protoreflect.EnumType {
	return &file_tpt_v1_tpt_proto_enumTypes[3]
}

func (x GridStressLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GridStressLevel.Descriptor instead.
func (GridStressLevel) EnumDescriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{3}
}

type ActuatorState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Device         string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Valve          float64                `protobuf:"fixed64,2,opt,name=valve,proto3" json:"valve,omitempty"`
	Fan            float64                `protobuf:"fixed64,3,opt,name=fan,proto3" json:"fan,omitempty"`
	Outlet         bool                   `protobuf:"varint,4,opt,name=outlet,proto3" json:"outlet,omitempty"`
	DischargeLimit float64                `protobuf:"fixed64,5,opt,name=discharge_limit,json=dischargeLimit,proto3" json:"discharge_limit,omitempty"`
	Mode           Mode                   `protobuf:"varint,6,opt,name=mode,proto3,enum=tpt.v1.Mode" json:"mode,omitempty"`
	LatchedSafe    bool                   `protobuf:"varint,7,opt,name=latched_safe,json=latchedSafe,proto3" json:"latched_safe,omitempty"`
	Reason         string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Operator       string                 `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	UpdatedAtUnix  int64                  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActuatorState) Reset() {
	*x = ActuatorState{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActuatorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActuatorState) ProtoMessage() {}

func (x *ActuatorState) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActuatorState.ProtoReflect.Descriptor instead.
func (*ActuatorState) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{0}
}

func (x *ActuatorState) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ActuatorState) GetValve() float64 {
	if x != nil {
		return x.Valve
	}
	return 0
}

func (x *ActuatorState) GetFan() float64 {
	if x != nil {
		return x.Fan
	}
	return 0
}

func (x *ActuatorState) GetOutlet() bool {
	if x != nil {
		return x.Outlet
	}
	return false
}

func (x *ActuatorState) GetDischargeLimit() float64 {
	if x != nil {
		return x.DischargeLimit
	}
	return 0
}

func (x *ActuatorState) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *ActuatorState) GetLatchedSafe() bool {
	if x != nil {
		return x.LatchedSafe
	}
	return false
}

func (x *ActuatorState) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ActuatorState) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ActuatorState) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Command       Command                `protobuf:"varint,4,opt,name=command,proto3,enum=tpt.v1.Command" json:"command,omitempty"`
	Requested     string                 `protobuf:"bytes,5,opt,name=requested,proto3" json:"requested,omitempty"` // JSON-encoded requested value
	Applied       string                 `protobuf:"bytes,6,opt,name=applied,proto3" json:"applied,omitempty"`     // JSON-encoded applied (post-clamp) value
	Clamped       bool                   `protobuf:"varint,7,opt,name=clamped,proto3" json:"clamped,omitempty"`
	Operator      string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	Note          string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{1}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *AuditEntry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *AuditEntry) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_UNSPECIFIED
}

func (x *AuditEntry) GetRequested() string {
	if x != nil {
		return x.Requested
	}
	return ""
}

func (x *AuditEntry) GetApplied() string {
	if x != nil {
		return x.Applied
	}
	return ""
}

func (x *AuditEntry) GetClamped() bool {
	if x != nil {
		return x.Clamped
	}
	return false
}

func (x *AuditEntry) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *AuditEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEntry) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GridStressSignal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          GridStressLevel        `protobuf:"varint,1,opt,name=level,proto3,enum=tpt.v1.GridStressLevel" json:"level,omitempty"`
	Score          float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"` // normalized 0..1 magnitude
	Source         string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	ObservedAtUnix int64                  `protobuf:"varint,4,opt,name=observed_at_unix,json=observedAtUnix,proto3" json:"observed_at_unix,omitempty"`
	Note           string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GridStressSignal) Reset() {
	*x = GridStressSignal{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridStressSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridStressSignal) ProtoMessage() {}

func (x *GridStressSignal) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridStressSignal.ProtoReflect.Descriptor instead.
func (*GridStressSignal) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{2}
}

func (x *GridStressSignal) GetLevel() GridStressLevel {
	if x != nil {
		return x.Level
	}
	return GridStressLevel_GRID_STRESS_UNSPECIFIED
}

func (x *GridStressSignal) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GridStressSignal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GridStressSignal) GetObservedAtUnix() int64 {
	if x != nil {
		return x.ObservedAtUnix
	}
	return 0
}

func (x *GridStressSignal) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{3}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*ActuatorState       `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{4}
}

func (x *ListDevicesResponse) GetDevices() []*ActuatorState {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{5}
}

func (x *GetStateRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type OverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Command       Command                `protobuf:"varint,2,opt,name=command,proto3,enum=tpt.v1.Command" json:"command,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded (number or bool)
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideRequest) Reset() {
	*x = OverrideRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideRequest) ProtoMessage() {}

func (x *OverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideRequest.ProtoReflect.Descriptor instead.
func (*OverrideRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{6}
}

func (x *OverrideRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *OverrideRequest) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_UNSPECIFIED
}

func (x *OverrideRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OverrideRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OverrideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Clamped       bool                   `protobuf:"varint,2,opt,name=clamped,proto3" json:"clamped,omitempty"`
	State         *ActuatorState         `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideResponse) Reset() {
	*x = OverrideResponse{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideResponse) ProtoMessage() {}

func (x *OverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideResponse.ProtoReflect.Descriptor instead.
func (*OverrideResponse) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{7}
}

func (x *OverrideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OverrideResponse) GetClamped() bool {
	if x != nil {
		return x.Clamped
	}
	return false
}

func (x *OverrideResponse) GetState() *ActuatorState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *OverrideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{8}
}

func (x *ResetRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ResetRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ResetRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatchRequest) Reset() {
	*x = LatchRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatchRequest) ProtoMessage() {}

func (x *LatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatchRequest.ProtoReflect.Descriptor instead.
func (*LatchRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{9}
}

func (x *LatchRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *LatchRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *LatchRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{10}
}

func (x *AuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{11}
}

func (x *AuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SetPowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	SystemId      string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // On/Off/GracefulShutdown/GracefulRestart/ForceOff/ForceRestart/PushPowerButton
	Via           string                 `protobuf:"bytes,4,opt,name=via,proto3" json:"via,omitempty"`       // "redfish" | "ipmi" | "" (auto)
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPowerRequest) Reset() {
	*x = SetPowerRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerRequest) ProtoMessage() {}

func (x *SetPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerRequest.ProtoReflect.Descriptor instead.
func (*SetPowerRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{12}
}

func (x *SetPowerRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SetPowerRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SetPowerRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SetPowerRequest) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

func (x *SetPowerRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SetPowerRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type SetBootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	SystemId      string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // Pxe/Hdd/Bios/...
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootRequest) Reset() {
	*x = SetBootRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootRequest) ProtoMessage() {}

func (x *SetBootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootRequest.ProtoReflect.Descriptor instead.
func (*SetBootRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{13}
}

func (x *SetBootRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SetBootRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SetBootRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SetBootRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SetBootRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type SetPowerCapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ChassisId     string                 `protobuf:"bytes,2,opt,name=chassis_id,json=chassisId,proto3" json:"chassis_id,omitempty"`
	CapW          float64                `protobuf:"fixed64,3,opt,name=cap_w,json=capW,proto3" json:"cap_w,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPowerCapRequest) Reset() {
	*x = SetPowerCapRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerCapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerCapRequest) ProtoMessage() {}

func (x *SetPowerCapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerCapRequest.ProtoReflect.Descriptor instead.
func (*SetPowerCapRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{14}
}

func (x *SetPowerCapRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SetPowerCapRequest) GetChassisId() string {
	if x != nil {
		return x.ChassisId
	}
	return ""
}

func (x *SetPowerCapRequest) GetCapW() float64 {
	if x != nil {
		return x.CapW
	}
	return 0
}

func (x *SetPowerCapRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SetPowerCapRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ResolveThrottleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []string               `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveThrottleRequest) Reset() {
	*x = ResolveThrottleRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveThrottleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveThrottleRequest) ProtoMessage() {}

func (x *ResolveThrottleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveThrottleRequest.ProtoReflect.Descriptor instead.
func (*ResolveThrottleRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveThrottleRequest) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ResolveThrottleResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Signal *GridStressSignal      `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	// ThrottleAction encoded inline (server_id, level, cap_w, shutdown).
	Actions       []*ThrottleAction `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveThrottleResponse) Reset() {
	*x = ResolveThrottleResponse{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveThrottleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveThrottleResponse) ProtoMessage() {}

func (x *ResolveThrottleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveThrottleResponse.ProtoReflect.Descriptor instead.
func (*ResolveThrottleResponse) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveThrottleResponse) GetSignal() *GridStressSignal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *ResolveThrottleResponse) GetActions() []*ThrottleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ThrottleAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Level         GridStressLevel        `protobuf:"varint,2,opt,name=level,proto3,enum=tpt.v1.GridStressLevel" json:"level,omitempty"`
	CapW          float64                `protobuf:"fixed64,3,opt,name=cap_w,json=capW,proto3" json:"cap_w,omitempty"`
	Shutdown      bool                   `protobuf:"varint,4,opt,name=shutdown,proto3" json:"shutdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrottleAction) Reset() {
	*x = ThrottleAction{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrottleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrottleAction) ProtoMessage() {}

func (x *ThrottleAction) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrottleAction.ProtoReflect.Descriptor instead.
func (*ThrottleAction) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{17}
}

func (x *ThrottleAction) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ThrottleAction) GetLevel() GridStressLevel {
	if x != nil {
		return x.Level
	}
	return GridStressLevel_GRID_STRESS_UNSPECIFIED
}

func (x *ThrottleAction) GetCapW() float64 {
	if x != nil {
		return x.CapW
	}
	return 0
}

func (x *ThrottleAction) GetShutdown() bool {
	if x != nil {
		return x.Shutdown
	}
	return false
}

type SubmitRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Device   string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Command  Command                `protobuf:"varint,2,opt,name=command,proto3,enum=tpt.v1.Command" json:"command,omitempty"`
	Value    string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded
	Operator string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Reason   string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// source identifies the caller (operator, ai_brain, hardware_api).
	Source        string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{18}
}

func (x *SubmitRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SubmitRequest) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_UNSPECIFIED
}

func (x *SubmitRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SubmitRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SubmitRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SubmitRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Clamped       bool                   `protobuf:"varint,2,opt,name=clamped,proto3" json:"clamped,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // rejection/clamp explanation
	State         *ActuatorState         `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{19}
}

func (x *SubmitResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitResponse) GetClamped() bool {
	if x != nil {
		return x.Clamped
	}
	return false
}

func (x *SubmitResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SubmitResponse) GetState() *ActuatorState {
	if x != nil {
		return x.State
	}
	return nil
}

type PolicyResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CritAirTempC float64                `protobuf:"fixed64,1,opt,name=crit_air_temp_c,json=critAirTempC,proto3" json:"crit_air_temp_c,omitempty"`
	WarnAirTempC float64                `protobuf:"fixed64,2,opt,name=warn_air_temp_c,json=warnAirTempC,proto3" json:"warn_air_temp_c,omitempty"`
	MinAirTempC  float64                `protobuf:"fixed64,3,opt,name=min_air_temp_c,json=minAirTempC,proto3" json:"min_air_temp_c,omitempty"`
	MinValve     float64                `protobuf:"fixed64,4,opt,name=min_valve,json=minValve,proto3" json:"min_valve,omitempty"`
	MaxValve     float64                `protobuf:"fixed64,5,opt,name=max_valve,json=maxValve,proto3" json:"max_valve,omitempty"`
	MinFan       float64                `protobuf:"fixed64,6,opt,name=min_fan,json=minFan,proto3" json:"min_fan,omitempty"`
	MaxFan       float64                `protobuf:"fixed64,7,opt,name=max_fan,json=maxFan,proto3" json:"max_fan,omitempty"`
	MinDischarge float64                `protobuf:"fixed64,8,opt,name=min_discharge,json=minDischarge,proto3" json:"min_discharge,omitempty"`
	MaxDischarge float64                `protobuf:"fixed64,9,opt,name=max_discharge,json=maxDischarge,proto3" json:"max_discharge,omitempty"`
	// require_two_person is true when manual overrides need a second ack.
	RequireTwoPerson bool `protobuf:"varint,10,opt,name=require_two_person,json=requireTwoPerson,proto3" json:"require_two_person,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicyResponse) Reset() {
	*x = PolicyResponse{}
	mi := &file_tpt_v1_tpt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResponse) ProtoMessage() {}

func (x *PolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpt_v1_tpt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResponse.ProtoReflect.Descriptor instead.
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return file_tpt_v1_tpt_proto_rawDescGZIP(), []int{20}
}

func (x *PolicyResponse) GetCritAirTempC() float64 {
	if x != nil {
		return x.CritAirTempC
	}
	return 0
}

func (x *PolicyResponse) GetWarnAirTempC() float64 {
	if x != nil {
		return x.WarnAirTempC
	}
	return 0
}

func (x *PolicyResponse) GetMinAirTempC() float64 {
	if x != nil {
		return x.MinAirTempC
	}
	return 0
}

func (x *PolicyResponse) GetMinValve() float64 {
	if x != nil {
		return x.MinValve
	}
	return 0
}

func (x *PolicyResponse) GetMaxValve() float64 {
	if x != nil {
		return x.MaxValve
	}
	return 0
}

func (x *PolicyResponse) GetMinFan() float64 {
	if x != nil {
		return x.MinFan
	}
	return 0
}

func (x *PolicyResponse) GetMaxFan() float64 {
	if x != nil {
		return x.MaxFan
	}
	return 0
}

func (x *PolicyResponse) GetMinDischarge() float64 {
	if x != nil {
		return x.MinDischarge
	}
	return 0
}

func (x *PolicyResponse) GetMaxDischarge() float64 {
	if x != nil {
		return x.MaxDischarge
	}
	return 0
}

func (x *PolicyResponse) GetRequireTwoPerson() bool {
	if x != nil {
		return x.RequireTwoPerson
	}
	return false
}

var File_tpt_v1_tpt_proto protoreflect.FileDescriptor

const file_tpt_v1_tpt_proto_rawDesc = "" +
	"\n" +
	"\x10tpt/v1/tpt.proto\x12\x06tpt.v1\"\xb1\x02\n" +
	"\rActuatorState\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05valve\x18\x02 \x01(\x01R\x05valve\x12\x10\n" +
	"\x03fan\x18\x03 \x01(\x01R\x03fan\x12\x16\n" +
	"\x06outlet\x18\x04 \x01(\bR\x06outlet\x12'\n" +
	"\x0fdischarge_limit\x18\x05 \x01(\x01R\x0edischargeLimit\x12 \n" +
	"\x04mode\x18\x06 \x01(\x0e2\f.tpt.v1.ModeR\x04mode\x12!\n" +
	"\flatched_safe\x18\a \x01(\bR\vlatchedSafe\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1a\n" +
	"\boperator\x18\t \x01(\tR\boperator\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\"\x92\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12)\n" +
	"\acommand\x18\x04 \x01(\x0e2\x0f.tpt.v1.CommandR\acommand\x12\x1c\n" +
	"\trequested\x18\x05 \x01(\tR\trequested\x12\x18\n" +
	"\aapplied\x18\x06 \x01(\tR\aapplied\x12\x18\n" +
	"\aclamped\x18\a \x01(\bR\aclamped\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note\"\xad\x01\n" +
	"\x10GridStressSignal\x12-\n" +
	"\x05level\x18\x01 \x01(\x0e2\x17.tpt.v1.GridStressLevelR\x05level\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12(\n" +
	"\x10observed_at_unix\x18\x04 \x01(\x03R\x0eobservedAtUnix\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\a\n" +
	"\x05Empty\"F\n" +
	"\x13ListDevicesResponse\x12/\n" +
	"\adevices\x18\x01 \x03(\v2\x15.tpt.v1.ActuatorStateR\adevices\")\n" +
	"\x0fGetStateRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"\x9e\x01\n" +
	"\x0fOverrideRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12)\n" +
	"\acommand\x18\x02 \x01(\x0e2\x0f.tpt.v1.CommandR\acommand\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x8b\x01\n" +
	"\x10OverrideResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aclamped\x18\x02 \x01(\bR\aclamped\x12+\n" +
	"\x05state\x18\x03 \x01(\v2\x15.tpt.v1.ActuatorStateR\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"Z\n" +
	"\fResetRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"Z\n" +
	"\fLatchRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"$\n" +
	"\fAuditRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"=\n" +
	"\rAuditResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.tpt.v1.AuditEntryR\aentries\"\xa0\x01\n" +
	"\x0fSetPowerRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x10\n" +
	"\x03via\x18\x04 \x01(\tR\x03via\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"\x8d\x01\n" +
	"\x0eSetBootRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\x90\x01\n" +
	"\x12SetPowerCapRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1d\n" +
	"\n" +
	"chassis_id\x18\x02 \x01(\tR\tchassisId\x12\x13\n" +
	"\x05cap_w\x18\x03 \x01(\x01R\x04capW\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"2\n" +
	"\x16ResolveThrottleRequest\x12\x18\n" +
	"\aservers\x18\x01 \x03(\tR\aservers\"}\n" +
	"\x17ResolveThrottleResponse\x120\n" +
	"\x06signal\x18\x01 \x01(\v2\x18.tpt.v1.GridStressSignalR\x06signal\x120\n" +
	"\aactions\x18\x02 \x03(\v2\x16.tpt.v1.ThrottleActionR\aactions\"\x8d\x01\n" +
	"\x0eThrottleAction\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12-\n" +
	"\x05level\x18\x02 \x01(\x0e2\x17.tpt.v1.GridStressLevelR\x05level\x12\x13\n" +
	"\x05cap_w\x18\x03 \x01(\x01R\x04capW\x12\x1a\n" +
	"\bshutdown\x18\x04 \x01(\bR\bshutdown\"\xb4\x01\n" +
	"\rSubmitRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12)\n" +
	"\acommand\x18\x02 \x01(\x0e2\x0f.tpt.v1.CommandR\acommand\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\x8b\x01\n" +
	"\x0eSubmitResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\aclamped\x18\x02 \x01(\bR\aclamped\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12+\n" +
	"\x05state\x18\x04 \x01(\v2\x15.tpt.v1.ActuatorStateR\x05state\"\xe7\x02\n" +
	"\x0ePolicyResponse\x12%\n" +
	"\x0fcrit_air_temp_c\x18\x01 \x01(\x01R\fcritAirTempC\x12%\n" +
	"\x0fwarn_air_temp_c\x18\x02 \x01(\x01R\fwarnAirTempC\x12#\n" +
	"\x0emin_air_temp_c\x18\x03 \x01(\x01R\vminAirTempC\x12\x1b\n" +
	"\tmin_valve\x18\x04 \x01(\x01R\bminValve\x12\x1b\n" +
	"\tmax_valve\x18\x05 \x01(\x01R\bmaxValve\x12\x17\n" +
	"\amin_fan\x18\x06 \x01(\x01R\x06minFan\x12\x17\n" +
	"\amax_fan\x18\a \x01(\x01R\x06maxFan\x12#\n" +
	"\rmin_discharge\x18\b \x01(\x01R\fminDischarge\x12#\n" +
	"\rmax_discharge\x18\t \x01(\x01R\fmaxDischarge\x12,\n" +
	"\x12require_two_person\x18\n" +
	" \x01(\bR\x10requireTwoPerson*c\n" +
	"\n" +
	"DeviceKind\x12\x1b\n" +
	"\x17DEVICE_KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04RACK\x10\x01\x12\a\n" +
	"\x03PDU\x10\x02\x12\a\n" +
	"\x03UPS\x10\x03\x12\x10\n" +
	"\fCOOLING_LOOP\x10\x04\x12\n" +
	"\n" +
	"\x06SERVER\x10\x05*W\n" +
	"\aCommand\x12\x17\n" +
	"\x13COMMAND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05VALVE\x10\x01\x12\a\n" +
	"\x03FAN\x10\x02\x12\n" +
	"\n" +
	"\x06OUTLET\x10\x03\x12\x13\n" +
	"\x0fDISCHARGE_LIMIT\x10\x04*<\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04AUTO\x10\x01\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x02\x12\b\n" +
	"\x04SAFE\x10\x03*Z\n" +
	"\x0fGridStressLevel\x12\x1b\n" +
	"\x17GRID_STRESS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\b\n" +
	"\x04MILD\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\xec\x02\n" +
	"\x0eControlService\x129\n" +
	"\vListDevices\x12\r.tpt.v1.Empty\x1a\x1b.tpt.v1.ListDevicesResponse\x12:\n" +
	"\bGetState\x12\x17.tpt.v1.GetStateRequest\x1a\x15.tpt.v1.ActuatorState\x12=\n" +
	"\bOverride\x12\x17.tpt.v1.OverrideRequest\x1a\x18.tpt.v1.OverrideResponse\x124\n" +
	"\x05Reset\x12\x14.tpt.v1.ResetRequest\x1a\x15.tpt.v1.ActuatorState\x128\n" +
	"\tLatchSafe\x12\x14.tpt.v1.LatchRequest\x1a\x15.tpt.v1.ActuatorState\x124\n" +
	"\x05Audit\x12\x14.tpt.v1.AuditRequest\x1a\x15.tpt.v1.AuditResponse2\x85\x02\n" +
	"\x0fHardwareService\x122\n" +
	"\bSetPower\x12\x17.tpt.v1.SetPowerRequest\x1a\r.tpt.v1.Empty\x120\n" +
	"\aSetBoot\x12\x16.tpt.v1.SetBootRequest\x1a\r.tpt.v1.Empty\x128\n" +
	"\vSetPowerCap\x12\x1a.tpt.v1.SetPowerCapRequest\x1a\r.tpt.v1.Empty\x12R\n" +
	"\x0fResolveThrottle\x12\x1e.tpt.v1.ResolveThrottleRequest\x1a\x1f.tpt.v1.ResolveThrottleResponse2A\n" +
	"\vGridService\x122\n" +
	"\aCurrent\x12\r.tpt.v1.Empty\x1a\x18.tpt.v1.GridStressSignal2x\n" +
	"\fOrchestrator\x127\n" +
	"\x06Submit\x12\x15.tpt.v1.SubmitRequest\x1a\x16.tpt.v1.SubmitResponse\x12/\n" +
	"\x06Policy\x12\r.tpt.v1.Empty\x1a\x16.tpt.v1.PolicyResponseBMZKgithub.com/TPT-Solutions/tpt-datacenter/api/internal/orchestration/pb;tptv1b\x06proto3"

var (
	file_tpt_v1_tpt_proto_rawDescOnce sync.Once
	file_tpt_v1_tpt_proto_rawDescData []byte
)

func file_tpt_v1_tpt_proto_rawDescGZIP() []byte {
	file_tpt_v1_tpt_proto_rawDescOnce.Do(func() {
		file_tpt_v1_tpt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpt_v1_tpt_proto_rawDesc), len(file_tpt_v1_tpt_proto_rawDesc)))
	})
	return file_tpt_v1_tpt_proto_rawDescData
}

var file_tpt_v1_tpt_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_tpt_v1_tpt_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tpt_v1_tpt_proto_goTypes = []any{
	(DeviceKind)(0),                 // 0: tpt.v1.DeviceKind
	(Command)(0),                    // 1: tpt.v1.Command
	(Mode)(0),                       // 2: tpt.v1.Mode
	(GridStressLevel)(0),            // 3: tpt.v1.GridStressLevel
	(*ActuatorState)(nil),           // 4: tpt.v1.ActuatorState
	(*AuditEntry)(nil),              // 5: tpt.v1.AuditEntry
	(*GridStressSignal)(nil),        // 6: tpt.v1.GridStressSignal
	(*Empty)(nil),                   // 7: tpt.v1.Empty
	(*ListDevicesResponse)(nil),     // 8: tpt.v1.ListDevicesResponse
	(*GetStateRequest)(nil),         // 9: tpt.v1.GetStateRequest
	(*OverrideRequest)(nil),         // 10: tpt.v1.OverrideRequest
	(*OverrideResponse)(nil),        // 11: tpt.v1.OverrideResponse
	(*ResetRequest)(nil),            // 12: tpt.v1.ResetRequest
	(*LatchRequest)(nil),            // 13: tpt.v1.LatchRequest
	(*AuditRequest)(nil),            // 14: tpt.v1.AuditRequest
	(*AuditResponse)(nil),           // 15: tpt.v1.AuditResponse
	(*SetPowerRequest)(nil),         // 16: tpt.v1.SetPowerRequest
	(*SetBootRequest)(nil),          // 17: tpt.v1.SetBootRequest
	(*SetPowerCapRequest)(nil),      // 18: tpt.v1.SetPowerCapRequest
	(*ResolveThrottleRequest)(nil),  // 19: tpt.v1.ResolveThrottleRequest
	(*ResolveThrottleResponse)(nil), // 20: tpt.v1.ResolveThrottleResponse
	(*ThrottleAction)(nil),          // 21: tpt.v1.ThrottleAction
	(*SubmitRequest)(nil),           // 22: tpt.v1.SubmitRequest
	(*SubmitResponse)(nil),          // 23: tpt.v1.SubmitResponse
	(*PolicyResponse)(nil),          // 24: tpt.v1.PolicyResponse
}
var file_tpt_v1_tpt_proto_depIdxs = []int32{
	2,  // 0: tpt.v1.ActuatorState.mode:type_name -> tpt.v1.Mode
	1,  // 1: tpt.v1.AuditEntry.command:type_name -> tpt.v1.Command
	3,  // 2: tpt.v1.GridStressSignal.level:type_name -> tpt.v1.GridStressLevel
	4,  // 3: tpt.v1.ListDevicesResponse.devices:type_name -> tpt.v1.ActuatorState
	1,  // 4: tpt.v1.OverrideRequest.command:type_name -> tpt.v1.Command
	4,  // 5: tpt.v1.OverrideResponse.state:type_name -> tpt.v1.ActuatorState
	5,  // 6: tpt.v1.AuditResponse.entries:type_name -> tpt.v1.AuditEntry
	6,  // 7: tpt.v1.ResolveThrottleResponse.signal:type_name -> tpt.v1.GridStressSignal
	21, // 8: tpt.v1.ResolveThrottleResponse.actions:type_name -> tpt.v1.ThrottleAction
	3,  // 9: tpt.v1.ThrottleAction.level:type_name -> tpt.v1.GridStressLevel
	1,  // 10: tpt.v1.SubmitRequest.command:type_name -> tpt.v1.Command
	4,  // 11: tpt.v1.SubmitResponse.state:type_name -> tpt.v1.ActuatorState
	7,  // 12: tpt.v1.ControlService.ListDevices:input_type -> tpt.v1.Empty
	9,  // 13: tpt.v1.ControlService.GetState:input_type -> tpt.v1.GetStateRequest
	10, // 14: tpt.v1.ControlService.Override:input_type -> tpt.v1.OverrideRequest
	12, // 15: tpt.v1.ControlService.Reset:input_type -> tpt.v1.ResetRequest
	13, // 16: tpt.v1.ControlService.LatchSafe:input_type -> tpt.v1.LatchRequest
	14, // 17: tpt.v1.ControlService.Audit:input_type -> tpt.v1.AuditRequest
	16, // 18: tpt.v1.HardwareService.SetPower:input_type -> tpt.v1.SetPowerRequest
	17, // 19: tpt.v1.HardwareService.SetBoot:input_type -> tpt.v1.SetBootRequest
	18, // 20: tpt.v1.HardwareService.SetPowerCap:input_type -> tpt.v1.SetPowerCapRequest
	19, // 21: tpt.v1.HardwareService.ResolveThrottle:input_type -> tpt.v1.ResolveThrottleRequest
	7,  // 22: tpt.v1.GridService.Current:input_type -> tpt.v1.Empty
	22, // 23: tpt.v1.Orchestrator.Submit:input_type -> tpt.v1.SubmitRequest
	7,  // 24: tpt.v1.Orchestrator.Policy:input_type -> tpt.v1.Empty
	8,  // 25: tpt.v1.ControlService.ListDevices:output_type -> tpt.v1.ListDevicesResponse
	4,  // 26: tpt.v1.ControlService.GetState:output_type -> tpt.v1.ActuatorState
	11, // 27: tpt.v1.ControlService.Override:output_type -> tpt.v1.OverrideResponse
	4,  // 28: tpt.v1.ControlService.Reset:output_type -> tpt.v1.ActuatorState
	4,  // 29: tpt.v1.ControlService.LatchSafe:output_type -> tpt.v1.ActuatorState
	15, // 30: tpt.v1.ControlService.Audit:output_type -> tpt.v1.AuditResponse
	7,  // 31: tpt.v1.HardwareService.SetPower:output_type -> tpt.v1.Empty
	7,  // 32: tpt.v1.HardwareService.SetBoot:output_type -> tpt.v1.Empty
	7,  // 33: tpt.v1.HardwareService.SetPowerCap:output_type -> tpt.v1.Empty
	20, // 34: tpt.v1.HardwareService.ResolveThrottle:output_type -> tpt.v1.ResolveThrottleResponse
	6,  // 35: tpt.v1.GridService.Current:output_type -> tpt.v1.GridStressSignal
	23, // 36: tpt.v1.Orchestrator.Submit:output_type -> tpt.v1.SubmitResponse
	24, // 37: tpt.v1.Orchestrator.Policy:output_type -> tpt.v1.PolicyResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tpt_v1_tpt_proto_init() }
func file_tpt_v1_tpt_proto_init() {
	if File_tpt_v1_tpt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpt_v1_tpt_proto_rawDesc), len(file_tpt_v1_tpt_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_tpt_v1_tpt_proto_goTypes,
		DependencyIndexes: file_tpt_v1_tpt_proto_depIdxs,
		EnumInfos:         file_tpt_v1_tpt_proto_enumTypes,
		MessageInfos:      file_tpt_v1_tpt_proto_msgTypes,
	}.Build()
	File_tpt_v1_tpt_proto = out.File
	file_tpt_v1_tpt_proto_goTypes = nil
	file_tpt_v1_tpt_proto_depIdxs = nil
}
